config/routes.rb
Rails.application.routes.draw do

  get 'urls/new'
  post 'urls/new' =>  'urls#create'
  get '/url/:id' => 'urls#show', as: 'url'

end

app/models/url.rb
class Url < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def show
    @url = Url.find(params[:id])
    redirect_to ("#{@url.input}")
  end

  def new
    @urls = Url.all
  end

  def create
    @url = Url.new(url_params)
    @url.save
    redirect_to urls_new_path(id: @url.id)
  end







  private

  def set_url
    @url = Url.find(params[:id])
  end

  def url_params
    params.require(:url).permit(:input, :id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Short</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/new.html.erb
<div class="container">
  <h1>Enter the URL you wish to shorten!</h1>
  <%= url_url(params[:id]) if params[:id] %>
  <%= form_for(:url) do |f| %>
  <div class="field">
    <%= f.label :input %>
    <%= f.text_field :input %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
</div>